//
//  AppData.swift
//  SteigerAndrewRateAPotty
//
//  Created by asteiger on 2/23/23.
//
//  Represents mock data and shared request/response models they would share
//  Assumed logic:
//  -data is sorted by highest rating
//  -potty id is unique, review id is wholly unique

import Foundation

// a mock api
class AppData {
    // set up singleton access
    private var _AppPotties: [Potty]
    var AppPotties: [Potty] {
        return _AppPotties
    }
    
    init() {
        self._AppPotties = PottyDataSet
    }
    
    // data mutations
    func addReview(_ pottyId: String, newReview: PottyReview) {
        var pottyIndex: Int?
        var ratingIndex: String = ""
        for i in 0..<PottyDataSet.count {
            if PottyDataSet[i].id == pottyId {
                pottyIndex = i
            }
            //  get next rating iteration, would be just a transaction sequence id that database would normally handle
            //  would also be guid's instead of int's
            for j in 0..<PottyDataSet[i].ratings.count {
                if ratingIndex < PottyDataSet[i].ratings[j].id {
                    ratingIndex = String(Int(PottyDataSet[i].ratings[j].id)! + 1)
                }
            }
        }
        if let i = pottyIndex {
            //  attach index to next review in sequence
            let indexedReview = PottyReview(id: ratingIndex, author: newReview.author, ratingAccessibility: newReview.ratingAccessibility, ratingCleanliness: newReview.ratingCleanliness, ratingAtmosphere: newReview.ratingAtmosphere, comment: newReview.comment, upVotes: 0, downVotes: 0)
            PottyDataSet[i].ratings.append(indexedReview)
        }
        // reset singleton object
        self._AppPotties = PottyDataSet
    }
    
    func incrementVote(_ id: String, upVote: Bool, increment: Bool) {
        for i in 0..<PottyDataSet.count {
            for j in 0..<PottyDataSet[i].ratings.count {
                if id == PottyDataSet[i].ratings[j].id {
                    if upVote {
                        if increment {
                            PottyDataSet[i].ratings[j].upVotes += 1
                        }
                        else {
                            PottyDataSet[i].ratings[j].upVotes -= 1
                        }
                    }
                    else {
                        if increment {
                            PottyDataSet[i].ratings[j].downVotes += 1
                        }
                        else {
                            PottyDataSet[i].ratings[j].downVotes -= 1
                        }
                    }
                }
            }
        }
        // reset singleton object
        self._AppPotties = PottyDataSet
    }
    
    func setUserCastVote(_ id: String, userCastVote: Bool?) {
        for i in 0..<PottyDataSet.count {
            for j in 0..<PottyDataSet[i].ratings.count {
                if id == PottyDataSet[i].ratings[j].id {
                    PottyDataSet[i].ratings[j].userCastVote = userCastVote
                }
            }
        }
        // reset singleton object
        self._AppPotties = PottyDataSet
    }
    
    // mock data sets
    private var PottyDataSet: [Potty] = [
        Potty(id: "0",
              ratings: [
                PottyReview(id: "0",
                            author: "justanotherjanitor99",
                            dateTimeCreated: Date.from(year: 2022, month: 01, day: 09, hour: 20, minute: 01),
                            ratingAccessibility: 2,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 4,
                            comment: "Hello, lifelong custodian here. i found this place to be pretty loud between stalls but easy to navigate for my essentials. Not very clean imo I have had my share of bad accidents but let me tell you a story bout i’d never forget. \nIt was an early autumn evening and my dog was riding shotgun when we both knew what it was time for. Right off of I71N we found this rest area that wasn’t on any signs and had to pull off immediately. \nThis was the day I met my wife.",
                            upVotes: 300,
                            downVotes: 12,
                           userCastVote: nil),
                PottyReview(id: "1",
                            author: "dogguy99",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 14, hour: 18, minute: 01),
                            ratingAccessibility: 2,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 5,
                            comment: "This place is amazing. I felt like i was in heaven if heaven was on the side of the road in back country Ohio. I’d never seen anything like this before but now I can say I have.",
                            upVotes: 3,
                            downVotes: 1648,
                            userCastVote: nil),
                PottyReview(id: "2",
                            author: "Anonymous3546",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 1,
                            ratingCleanliness: 1,
                            ratingAtmosphere: 0,
                            comment: "meh",
                            upVotes: 46,
                            downVotes: 9,
                            userCastVote: nil),
                PottyReview(id: "3",
                            author: "petboy98",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 3,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 3,
                            comment: "No bathroomspace for pets for this I will deduct one star.\nMy dog was unhappy with trees deduct one star.",
                            upVotes: 5,
                            downVotes: 5,
                            userCastVote: nil),
                PottyReview(id: "4",
                            author: "ancientburro",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 1,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 0,
                            comment: "This bathroom is clean",
                            upVotes: 62,
                            downVotes: 0,
                            userCastVote: nil),
                PottyReview(id: "5",
                            author: "elephantmans",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 1,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 0,
                            comment: "This bathroom was so clean i let my toddler lick the floor",
                            upVotes: 22,
                            downVotes: 1,
                            userCastVote: nil),
                PottyReview(id: "6",
                            author: "elephantmans",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 1,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 0,
                            comment: "I reviewed again",
                            upVotes: 0,
                            downVotes: 33,
                            userCastVote: nil),
                PottyReview(id: "7",
                            author: "momsquad4",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 0,
                            ratingCleanliness: 0,
                            ratingAtmosphere: 0,
                            comment: "nasty",
                            upVotes: 5,
                            downVotes: 3,
                            userCastVote: nil),
                PottyReview(id: "8",
                            author: "al",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 1,
                            ratingCleanliness: 1,
                            ratingAtmosphere: 1,
                            comment: "",
                            upVotes: 0,
                            downVotes: 3,
                            userCastVote: nil),
                PottyReview(id: "9",
                            author: "eggman",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 2,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 2,
                            comment: "A little bit of an afterthought when it comes to this place",
                            upVotes: 4,
                            downVotes: 12,
                            userCastVote: nil),
                PottyReview(id: "10",
                            author: "benedictarnold4",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 2,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 4,
                            comment: "excellent",
                            upVotes: 0,
                            downVotes: 0,
                            userCastVote: nil),
                PottyReview(id: "11",
                            author: "therealfrankzappa",
                            dateTimeCreated: Date.from(year: 2023, month: 03, day: 24, hour: 18, minute: 01),
                            ratingAccessibility: 2,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 4,
                            comment: "i was here",
                            upVotes: 0,
                            downVotes: 0,
                            userCastVote: nil),
              ],
              owner: "johnthejanitor",
              latitude: -30.86,
              longitude: 150.20,
              title: "Desert Paradise",
              snippet: "Australia",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "1",
              ratings: [
                PottyReview(id: "12",
                            author: "justanotherjanitor",
                            dateTimeCreated: Date.from(year: 2022, month: 09, day: 14, hour: 12, minute: 12),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 5,
                            comment: "some comment",
                            upVotes: 3,
                            downVotes: 1,
                            userCastVote: nil),
              ],
              latitude: -30.16,
              longitude: 151.20,
              title: "Desert Tundra",
              snippet: "Australia",
              iconView: AppAssets.ImageViews.PortaPottyView35),
        Potty(id: "2",
              ratings: [
                PottyReview(
                    id: "13",
                    author: "SanFranGal",
                    dateTimeCreated: Date.from(year: 2023, month: 03, day: 08, hour: 14, minute: 27),
                    ratingAccessibility: 5,
                    ratingCleanliness: 4,
                    ratingAtmosphere: 3,
                    comment: "A great place to take a break while walking through the park. Clean and accessible.",
                    upVotes: 10,
                    downVotes: 2,
                    userCastVote: nil),
              ],
              latitude: 37.7749,
              longitude: -122.4194,
              title: "Golden Gate Park Restroom",
              snippet: "Public restroom in Golden Gate Park",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(
            id: "2",
            ratings: [],
            latitude: 45.5231,
            longitude: -122.6765,
            title: "City Potty",
            snippet: "Portland",
            iconView: AppAssets.ImageViews.PortaPottyView35),
        
        Potty(id: "3",
              ratings: [
                PottyReview(id: "14",
                            author: "pottylover101",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 01, hour: 13, minute: 42),
                            ratingAccessibility: 4,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 2,
                            comment: "This Potty was just okay. It was pretty clean, but the atmosphere was lacking. There was also only one stall, which was kind of inconvenient.",
                            upVotes: 12,
                            downVotes: 4,
                            userCastVote: nil),
                PottyReview(id: "15",
                            author: "toilettraveler",
                            dateTimeCreated: Date.from(year: 2022, month: 08, day: 22, hour: 09, minute: 27),
                            ratingAccessibility: 3,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 4,
                            comment: "I stopped at this Potty on a road trip and was pleasantly surprised. It was clean and had a decent atmosphere. The only downside was that there was only one stall.",
                            upVotes: 7,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "16",
                            author: "johnsmith",
                            dateTimeCreated: Date.from(year: 2022, month: 05, day: 16, hour: 16, minute: 55),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 5,
                            comment: "This is hands down the best Potty I've ever been to. It was so clean and well-maintained, and the atmosphere was great. There were also multiple stalls, which was a huge plus. Highly recommend!",
                            upVotes: 23,
                            downVotes: 1,
                            userCastVote: nil),
              ],
              owner: "pottyowner123",
              latitude: 40.7128,
              longitude: -74.0060,
              title: "City Oasis",
              snippet: "New York, United States",
              iconView: AppAssets.ImageViews.PortaPottyView35),
        Potty(id: "2",
              ratings: [
                PottyReview(id: "17",
                            author: "toilettalker",
                            dateTimeCreated: Date.from(year: 2022, month: 05, day: 19, hour: 15, minute: 30),
                            ratingAccessibility: 4,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 3,
                            comment: "This restroom was conveniently located and easy to find. The toilet paper was well-stocked, and the sink had plenty of soap. However, the restroom was a bit crowded and there was a long line, which was frustrating.",
                            upVotes: 56,
                            downVotes: 8,
                            userCastVote: nil),
                PottyReview(id: "18",
                            author: "cleanfreak123",
                            dateTimeCreated: Date.from(year: 2022, month: 12, day: 08, hour: 10, minute: 45),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 5,
                            comment: "This restroom was spotless and smelled fresh. The lighting was perfect, and the hand dryer was really effective. I highly recommend this restroom to anyone traveling through the area.",
                            upVotes: 120,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "19",
                            author: "roadtripper456",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 28, hour: 14, minute: 10),
                            ratingAccessibility: 3,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 2,
                            comment: "This restroom was just okay. The toilet was a bit hard to flush, and the sink was dripping. Also, the restroom had a weird smell. However, it was better than nothing when I was on the road.",
                            upVotes: 7,
                            downVotes: 0,
                            userCastVote: nil),
              ],
              owner: "reststopcorp",
              latitude: 33.6846,
              longitude: -117.8265,
              title: "Riverside Rest Stop",
              snippet: "Riverside, California, USA",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "3",
              ratings: [
                PottyReview(id: "20",
                            author: "pottyfinder23",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 15, hour: 11, minute: 30),
                            ratingAccessibility: 4,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 2,
                            comment: "The location of this Potty was a bit difficult to find, but once I got there, it was okay. The accessibility was decent, but the cleanliness and atmosphere could have been better. Overall, an average experience.",
                            upVotes: 10,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "21",
                            author: "longdrive24",
                            dateTimeCreated: Date.from(year: 2022, month: 05, day: 22, hour: 17, minute: 45),
                            ratingAccessibility: 5,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 3,
                            comment: "This is a decent Potty to stop by during a long drive. The accessibility is good and it's easy to find. It could be cleaner though, and the atmosphere could be improved. Overall, it's an okay option on the highway.",
                            upVotes: 25,
                            downVotes: 5,
                            userCastVote: nil),
                PottyReview(id: "22",
                            author: "adventurer99",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 18, hour: 10, minute: 15),
                            ratingAccessibility: 3,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 1,
                            comment: "This Potty was a disappointment. The accessibility was not great and the cleanliness was poor. The atmosphere was not welcoming either. I would not recommend stopping here.",
                            upVotes: 2,
                            downVotes: 20,
                            userCastVote: nil),
              ],
              owner: "highwayreststopco",
              latitude: 37.22,
              longitude: -121.86,
              title: "Highway Rest Stop",
              snippet: "San Jose, California, USA",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "4",
              ratings: [
                PottyReview(id: "23",
                            author: "toilettalks",
                            dateTimeCreated: Date.from(year: 2022, month: 05, day: 22, hour: 10, minute: 30),
                            ratingAccessibility: 4,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 2,
                            comment: "This potty was alright. The accessibility was pretty good and the cleanliness was average. However, the atmosphere was quite unpleasant, and there was a weird smell lingering in the air. Overall, it was an okay experience.",
                            upVotes: 10,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "24",
                            author: "pottylover88",
                            dateTimeCreated: Date.from(year: 2022, month: 06, day: 18, hour: 14, minute: 45),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 4,
                            comment: "I loved this potty! It was so clean and well-maintained. The accessibility was great, and the atmosphere was pretty good too. The only downside was that it was a bit crowded, but that's to be expected at a rest stop. Overall, I highly recommend this potty!",
                            upVotes: 25,
                            downVotes: 1,
                            userCastVote: nil),
                PottyReview(id: "25",
                            author: "johnthejanitor",
                            dateTimeCreated: Date.from(year: 2022, month: 08, day: 02, hour: 08, minute: 00),
                            ratingAccessibility: 4,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 3,
                            comment: "As the owner of this potty, I take pride in keeping it clean and accessible for all. I'm glad to see that our efforts are appreciated by our users. We are always looking for ways to improve, so please let us know if you have any suggestions!",
                            upVotes: 15,
                            downVotes: 3,
                            userCastVote: nil),
                PottyReview(id: "26",
                            author: "reststoprookie",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 10, hour: 11, minute: 30),
                            ratingAccessibility: 3,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 1,
                            comment: "This potty was not great. The accessibility was okay, but the cleanliness was poor, and the atmosphere was terrible. It felt like I was walking into a horror movie. I would not recommend this potty to anyone.",
                            upVotes: 2,
                            downVotes: 50,
                            userCastVote: nil),
              ],
              owner: "johnthejanitor",
              latitude: 52.23,
              longitude: 21.01,
              title: "Clean & Cozy",
              snippet: "Warsaw, Poland",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "5",
              ratings: [
                PottyReview(id: "27",
                            author: "lovetotravel",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 20, hour: 10, minute: 30),
                            ratingAccessibility: 4,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 3,
                            comment: "This is a nice rest stop. Clean and easy to access. The atmosphere could be improved, but it's still a good place to take a break on a road trip.",
                            upVotes: 50,
                            downVotes: 10,
                            userCastVote: nil),
                PottyReview(id: "28",
                            author: "roadtripper",
                            dateTimeCreated: Date.from(year: 2022, month: 05, day: 12, hour: 15, minute: 45),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 5,
                            comment: "I stopped here on a road trip and was pleasantly surprised! This is one of the cleanest rest stops I've ever been to. The atmosphere is great too. Highly recommend!",
                            upVotes: 100,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "29",
                            author: "traveler1",
                            dateTimeCreated: Date.from(year: 2021, month: 11, day: 30, hour: 8, minute: 20),
                            ratingAccessibility: 3,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 2,
                            comment: "Decent rest stop, but nothing special. It could be cleaner and the atmosphere could be improved. It's good enough for a quick break on a road trip though.",
                            upVotes: 20,
                            downVotes: 5,
                            userCastVote: nil),
              ],
              owner: "travelstopnz",
              latitude: -36.85,
              longitude: 174.76,
              title: "Auckland Rest Stop",
              snippet: "Auckland, New Zealand",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "6",
              ratings: [
                PottyReview(id: "30",
                            author: "pottylover",
                            dateTimeCreated: Date.from(year: 2021, month: 06, day: 22, hour: 14, minute: 30),
                            ratingAccessibility: 4,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 2,
                            comment: "このトイレは利用しやすかったですが、清潔さは少し問題がありました。雰囲気もあまり良くありませんでした。",
                            upVotes: 10,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "31",
                            author: "toiletman",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 05, hour: 9, minute: 45),
                            ratingAccessibility: 5,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 3,
                            comment: "このトイレは非常に便利で、清潔感もあります。雰囲気も良く、快適に利用することができました。",
                            upVotes: 15,
                            downVotes: 0,
                            userCastVote: nil),
                PottyReview(id: "32",
                            author: "sakura_toilets",
                            dateTimeCreated: Date.from(year: 2022, month: 11, day: 17, hour: 16, minute: 15),
                            ratingAccessibility: 3,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 1,
                            comment: "このトイレは非常に使いにくく、清潔さも悪いです。雰囲気も最悪で、できるだけ利用しないようにしています。",
                            upVotes: 2,
                            downVotes: 20,
                            userCastVote: nil),
              ],
              owner: "toilet_king",
              latitude: 35.6895,
              longitude: 139.6917,
              title: "Tokyo Station Toilets",
              snippet: "Tokyo, Japan",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "7",
              ratings: [
                PottyReview(id: "33",
                            author: "josesierra",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 20, hour: 14, minute: 30),
                            ratingAccessibility: 4,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 3,
                            comment: "El baño estaba un poco sucio, pero la accesibilidad era buena. Me gustó el ambiente, aunque podría ser mejor. En general, una buena experiencia. ",
                            upVotes: 50,
                            downVotes: 7,
                            userCastVote: nil),
                PottyReview(id: "34",
                            author: "marialopez",
                            dateTimeCreated: Date.from(year: 2022, month: 05, day: 12, hour: 17, minute: 20),
                            ratingAccessibility: 3,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 4,
                            comment: "El baño es limpio y cómodo. La accesibilidad es buena y el ambiente es agradable. Recomendado.",
                            upVotes: 25,
                            downVotes: 5,
                            userCastVote: nil),
                PottyReview(id: "35",
                            author: "carlos123",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 07, hour: 13, minute: 05),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 5,
                            comment: "Este es el mejor baño que he usado en mi vida. La accesibilidad es excelente, la limpieza es impecable y el ambiente es perfecto. Definitivamente lo recomiendo.",
                            upVotes: 150,
                            downVotes: 2,
                            userCastVote: nil),
              ],
              owner: "hotelsanmiguel",
              latitude: 19.43,
              longitude: -99.13,
              title: "Hotel San Miguel",
              snippet: "Ciudad de México, México",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "8",
              ratings: [
                PottyReview(id: "36",
                            author: "toilet_tales",
                            dateTimeCreated: Date.from(year: 2021, month: 11, day: 25, hour: 13, minute: 30),
                            ratingAccessibility: 3,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 2,
                            comment: "Not the best toilet experience I've had, but it'll do in a pinch. Cleanliness was average and the atmosphere could have been better. It was also a bit of a tight squeeze, so not the most accessible toilet I've used. But hey, it's a public toilet, what more can you expect?",
                            upVotes: 22,
                            downVotes: 5,
                            userCastVote: nil),
                PottyReview(id: "37",
                            author: "thronequeen",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 10, hour: 16, minute: 45),
                            ratingAccessibility: 4,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 4,
                            comment: "This is one of the better public toilets I've used. It was clean, spacious and had a pleasant atmosphere. The only downside is that it's not very accessible for those with mobility issues, but overall a great experience.",
                            upVotes: 130,
                            downVotes: 3,
                            userCastVote: nil),
                PottyReview(id: "38",
                            author: "loo_lover",
                            dateTimeCreated: Date.from(year: 2022, month: 03, day: 08, hour: 10, minute: 20),
                            ratingAccessibility: 3,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 2,
                            comment: "Not the cleanest or most comfortable toilet, but it's functional. The accessibility is okay, but could be better. The atmosphere is nothing special, but it's better than nothing.",
                            upVotes: 10,
                            downVotes: 8,
                            userCastVote: nil),
                PottyReview(id: "39",
                            author: "thronethrower",
                            dateTimeCreated: Date.from(year: 2021, month: 07, day: 02, hour: 14, minute: 15),
                            ratingAccessibility: 2,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 1,
                            comment: "Absolutely horrible toilet experience. It was filthy, cramped, and had a terrible smell. The accessibility was non-existent, and the atmosphere was depressing. Avoid at all costs!",
                            upVotes: 2,
                            downVotes: 225,
                            userCastVote: nil),
              ],
              owner: "clean_and_tidy",
              latitude: 51.5074,
              longitude: -0.1278,
              title: "London Lavatory",
              snippet: "London, United Kingdom",
              iconView: AppAssets.ImageViews.RestAreaView35),
        Potty(id: "9",
              ratings: [
                PottyReview(id: "40",
                            author: "sitzpinkler",
                            dateTimeCreated: Date.from(year: 2023, month: 01, day: 15, hour: 14, minute: 01),
                            ratingAccessibility: 4,
                            ratingCleanliness: 2,
                            ratingAtmosphere: 3,
                            comment: "Etwas schmutzig aber sehr einfach zu finden. Nicht sehr geräumig, aber gut für eine schnelle Pause.",
                            upVotes: 42,
                            downVotes: 7,
                            userCastVote: nil),
                PottyReview(id: "41",
                            author: "klotuersteher",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 24, hour: 11, minute: 45),
                            ratingAccessibility: 5,
                            ratingCleanliness: 5,
                            ratingAtmosphere: 4,
                            comment: "Sehr sauber und gut organisiert. Der Duft von Lavendel war eine nette Überraschung. Ich würde wieder hierher kommen.",
                            upVotes: 97,
                            downVotes: 2,
                            userCastVote: nil),
                PottyReview(id: "42",
                            author: "pinkelprofi",
                            dateTimeCreated: Date.from(year: 2023, month: 02, day: 25, hour: 09, minute: 30),
                            ratingAccessibility: 3,
                            ratingCleanliness: 4,
                            ratingAtmosphere: 2,
                            comment: "Nicht der beste Ort, aber es wird seinen Zweck erfüllen. Kann etwas lauter sein als ich es normalerweise bevorzuge.",
                            upVotes: 10,
                            downVotes: 23,
                            userCastVote: nil),
                PottyReview(id: "43",
                            author: "pipigirl",
                            dateTimeCreated: Date.from(year: 2022, month: 12, day: 31, hour: 23, minute: 59),
                            ratingAccessibility: 4,
                            ratingCleanliness: 3,
                            ratingAtmosphere: 3,
                            comment: "Nicht schlecht, aber auch nicht großartig. Ich würde hier wieder anhalten, wenn ich in der Gegend bin.",
                            upVotes: 5,
                            downVotes: 0,
                            userCastVote: nil),
              ],
              owner: "pottymaster69",
              latitude: 52.52,
              longitude: 13.40,
              title: "Berlin Central Station",
              snippet: "Berlin, Germany",
              iconView: AppAssets.ImageViews.RestAreaView35),
    ]
}
